// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfbuazswgsyvgxbwijcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmYnVhenN3Z3N5dmd4YndpamNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Mjc5MzYsImV4cCI6MjA3MzMwMzkzNn0.enzOIzwiCPgMQNcA9Q6vyS8oeIGo27pP-8GEnbHnRbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});